// src/components/features/disclaimer/disclaimer-texts.ts

import type { LocaleCode } from "@/lib/i18n/messages";

/**
 * EU AI Act Art. 50 transparency disclaimer texts.
 * Bilingual support (es/en) for all disclaimer components.
 */
export const DISCLAIMER_TEXTS: Record<
  LocaleCode,
  {
    sessionBanner: string;
    sessionBannerTitle: string;
    aiIndicator: string;
    legalFooter: string;
  }
> = {
  es: {
    sessionBannerTitle: "Aviso de transparencia — IA Act Art. 50",
    sessionBanner:
      "Estás interactuando con un sistema de inteligencia artificial. " +
      "Las respuestas son generadas automáticamente por Anclora Advisor AI y no sustituyen " +
      "el asesoramiento profesional de un experto cualificado.",
    aiIndicator: "Respuesta generada por IA",
    legalFooter:
      "Esta respuesta no constituye asesoramiento legal ni fiscal profesional. " +
      "Consulte siempre con un profesional cualificado antes de tomar decisiones " +
      "basadas en esta información.",
  },
  en: {
    sessionBannerTitle: "Transparency notice — AI Act Art. 50",
    sessionBanner:
      "You are interacting with an artificial intelligence system. " +
      "Responses are automatically generated by Anclora Advisor AI and do not replace " +
      "professional advice from a qualified expert.",
    aiIndicator: "AI-generated response",
    legalFooter:
      "This response does not constitute professional legal or tax advice. " +
      "Always consult a qualified professional before making decisions " +
      "based on this information.",
  },
};
